### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by lavryniuk-dev** [totallyDev/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by tony-IronMan** [comment]
I strive to reduce global warming through sustainable production and consumption of energy, 
reducing the "risk of human extinction" by "making our civilization multi-planetary" and setting 
up a human colony on Mars.
