### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by lavryniuk-dev** [totallyDev/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by tony-IronMan** [comment]
elon.musk@tesla.com (add gmail icon)
1-800-613-8840 (add phone icon)
Los Angeles, USA (add location icon)
elon.musk (add skype icon)
