### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by lavryniuk-dev** [totallyDev/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by tony-IronMan** [comment]
**Skills & Competences**

Thinking through first principles 100%

Micromanaging 95%

Goal oriented 100%

Future focused 100%

Critical thinking 97%

Resiliency 100%

Verbal and written communication 90%

Leadership 99%

Creativity 93%

Time Management 100%


**Achievements & Certificates**

IEEE Honorary Membership (2015)
Given to people who have rendered meritorious service to humanity in the
IEEE`s designated fields of interest.

Businessperson of the Year by Fortune Magazine (2013)
Prize received for the following companies: 'SpaceX', 'Tesla Motors' and
'SolarCiry'.

FAI Gold Space Medal (2010)
One of the highest honors in the aerospace industry, shared with prominent
personalities like Neil Armstrong and John Glenn.

Honorary doctorate in Design from the Art Center College of Design

Honorary doctorate (DUniv) in Aerospace Engineering from the University of Surrey

Honorary doctorate of Engineering and Technology from Yale University


**Languages**

English
Afrikaans


**Inerests**

Physics | Sustainability | Philanthropy | Extraterrestrial life |
Alternative energy sources | Space engineering | Reading |
Video games
